unit TestRtfBase;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, SysUtils;

type

  TRtfTestCase = class(TTestCase)
  private
    FAssetPath: String;
    FStr: TStringList;
  protected
    property AssetPath: String read FAssetPath write FAssetPath;
    property Str: TStringList read FStr;
  public
    constructor Create(AName: string); override;
    destructor Destroy; override;
  end;

implementation

constructor TRtfTestCase.Create(AName: string);
begin
  inherited Create(AName);
  FStr := TStringList.Create;
  FStr.LineBreak := '';
  FAssetPath := '..\..\..\..\testdocs\';
end;

destructor TRtfTestCase.Destroy;
begin
  FreeAndNil(FStr);
  inherited;
end;

end.

